kind: Deployment
apiVersion: apps/v1
metadata:
  name: swytch-todos
  labels:
    app.kubernetes.io/name: swytch-todos
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app.kubernetes.io/name: swytch-todos
  template:
    metadata:
      labels:
        app.kubernetes.io/name: swytch-todos
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
        - name: swytch-todos
          image: "{{.Values.image.repository}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: '4'
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: SERVER_NAME
              value: ":80"
            - name: RETHINKDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: swytch-auth
                  key: rethinkdb-database
            - name: RETHINKDB_USER
              valueFrom:
                secretKeyRef:
                  name: swytch-auth
                  key: rethinkdb-user
            - name: RETHINKDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: swytch-auth
                  key: rethinkdb-password
            - name: RETHINKDB_HOST
              valueFrom:
                secretKeyRef:
                  name: swytch-auth
                  key: rethinkdb-host
