kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: todos-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/issue-temporary-certificate: 'true'
    certmanager.k8s.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/auth-signin: https://auth.getswytch.com/login
    nginx.ingress.kubernetes.io/auth-url: http://swytch-auth.auth.svc.cluster.local/api/auth?roles=user
    nginx.ingress.kubernetes.io/auth-keepalive: "5"
    nginx.ingress.kubernetes.io/auth-signin-redirect-param: "rd"
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
spec:
  ingressClassName: nginx
  tls:
    - secretName: auth-test-tls
      hosts:
        - todos.getswytch.com
  rules:
    - host: todos.getswytch.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: swytch-todos
                port:
                  number: 80
