kind: Secret
apiVersion: v1
metadata:
  name: swytch-auth
stringData:
  rethinkdb-host: {{.Values.rethinkdb.host}}
  rethinkdb-user: {{.Values.rethinkdb.user}}
  rethinkdb-password: {{.Values.rethinkdb.password}}
  rethinkdb-database: {{.Values.rethinkdb.database}}
