apiVersion: v1
kind: Service
metadata:
  name: swytch-todos
  labels:
    helm.sh/chart: {{ include "deployment.chart" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: swytch-todos
spec:
  type: ClusterIP
  ports:
    - targetPort: http
      port: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: swytch-todos
